# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/freelancer_tracker
spring.datasource.username=your_app_name
spring.datasource.password=your_password

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=example@gmail.com
spring.mail.password=your_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server
server.port=8080

# CORS
spring.mvc.cors.allowed-origins=http://localhost:4200

# AI
groq.api.key=your_key